# Generated by Django 5.2.4 on 2026-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('abhaId', models.CharField(blank=True, max_length=50)),
                ('complaint', models.TextField()),
                ('prakriti', models.TextField()),
                ('vikriti', models.TextField()),
                ('sara', models.TextField()),
                ('samhanana', models.TextField()),
                ('pramana', models.TextField()),
                ('satmya', models.TextField()),
                ('satva', models.TextField()),
                ('ahara_shakti', models.TextField()),
                ('vyayama_shakti', models.TextField()),
                ('vaya', models.CharField(choices=[('childhood', 'Childhood'), ('middle_age', 'Middle Age'), ('old_age', 'Old Age')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
