# Generated by Django 5.2.4 on 2026-09-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medikiosk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='abhaId',
            new_name='abha',
        ),
    ]
