# Generated by Django 6.1.1 on 2026-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikiosk', '0002_rename_abhaid_patient_abha'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='abha',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaya',
            field=models.CharField(choices=[('bala', 'Bala'), ('madhya', 'Madhya'), ('vriddha', 'Vriddha')], max_length=20),
        ),
    ]
