# Generated by Django 6.1.1 on 2026-09-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikiosk', '0003_patient_is_verified_patient_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='medical_documents/')),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('raw_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='medikiosk.patient')),
            ],
        ),
    ]
