# Generated by Django 6.1.1 on 2026-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikiosk', '0004_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
